Add client secret support
HyCraftHD/Minecraft-Authenticator pull request #3
Opened 2022-02-21 18:44 UTC by AppleDash

2022-02-21 20:09 UTC, HyCraftHD requested changes
LGTM. When the issue is resolved i can merge 👍

2022-02-21 20:09 UTC, HyCraftHD commented on src/main/java/net/hycrafthd/minecraft_authenticator/microsoft/service/MicrosoftService.java
> +		return oAuthLoginUrl(clientId, redirectUrl);
This should call the this method instead of it self:
``oAuthLoginUrl(String clientId, String redirectUrl, String clientSecret)``

2022-02-21 20:30 UTC, AppleDash commented
Fixed, thank you!

2022-02-21 21:47 UTC, HyCraftHD approved these changes

2022-02-21 21:47 UTC, merged

2022-02-22 01:18 UTC, HyCraftHD commented
3.0.1 includes this pr. Thanks again!